descriptor_extension: yml
version: '0.5'
package:
  vendor: eu.5gtango
  name: ns-mediapilot-service
  version: '0.8'
  maintainer: Ignacio Dominguez
  description: This is the NEW 5GTANGO network service for the media pilot with monitoring, Twitter and Youtube VNF
    integrated
files:
- path: Definitions/cms-vnfd.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: Definitions/ma-vnfd.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: Definitions/mse-cache-vnfd.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: Definitions/mse-transcode-vnfd.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: Definitions/twitter-vnfd.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: Definitions/youtube-vnfd.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
- path: Definitions/mediapilot-ns.yml
  type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango

